[package]
name = "mining_hw2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
csv = "1.1.6"
serde = "1.0.136"
serde_derive = "1.0.136"
